/*
 * This source file was generated by the Gradle 'init' task
 */
package top.srcres.apps.rustjnidemo;

import java.io.File;
import java.nio.file.Path;

public class App {
    static void loadRustLibrary() {
        String currentPathStr = System.getProperty("user.dir");
        System.out.println("Program is running in: " + currentPathStr);

        Path currentPath = new File(currentPathStr).toPath();
        Path libPath = currentPath.getParent().getParent()
                .resolve("rust")
                .resolve("target")
                .resolve("release")
                .resolve("librust_jni_demo.so");
        String libPathStr = libPath.toFile().getAbsolutePath();
        System.out.println("Loading Rust library at: " + libPathStr);
        System.load(libPathStr);
    }

    static int testInt;
    static String testString;

    static native String hello(String input);
    static native int helloInt(int input);
    static native int helloFromTestIntField();
    static native String helloFromTestStringField();

    public static void main(String[] args) {
        loadRustLibrary();

        String output = hello("string from Java");
        System.out.println(output);

        int outputInt = helloInt(114514);
        System.out.println(outputInt);

        testInt = 514;
        System.out.println(helloFromTestIntField());

        testString = "String static field from Java";
        System.out.println(helloFromTestStringField());
    }
}
