/*
 * This source file was generated by the Gradle 'init' task
 */
package top.srcres.apps.rustjnidemo;

import java.io.File;
import java.nio.file.Path;

public class App {
    static void loadRustLibrary() {
        System.out.println(System.getProperty("java.library.path"));
        System.loadLibrary("rust_jni_demo");
    }

    static int testInt;
    static String testString;
    static String testStringFromRust;

    static native String hello(String input);
    static native int helloInt(int input);
    static native int helloFromTestIntField();
    static native String helloFromTestStringField();
    static native void modifyTestStringFromRust(String input);
    static String callFromRust(String input) {
        System.out.println("Method callFromRust was invoked!");
        return "Java-side received: " + input;
    }
    static native String actCallFromRust(String input);
    static native void delayInRust(long timeMillis);

    public static void main(String[] args) {
        loadRustLibrary();

        String output = hello("string from Java");
        System.out.println(output);

        int outputInt = helloInt(114514);
        System.out.println(outputInt);

        testInt = 514;
        System.out.println(helloFromTestIntField());

        testString = "String static field from Java";
        System.out.println(helloFromTestStringField());

        modifyTestStringFromRust("string from Java #2");
        System.out.println(testStringFromRust);

        System.out.println("actCallFromRust result: " + actCallFromRust("string from Java #3"));

        System.out.println("Delay in Rust for 2 seconds...");
        delayInRust(2000);
        System.out.println("Delay done.");
    }
}
